### ISSUE TITLE
heads up deprecated cloudgenix-api-client

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#1]
@jchristn I just want to give you a heads up that I have deprecated/archived the [cloudgenix-api-client](https://github.com/sumitgoelpw/cloudgenix-api-client) repo in favor of your official SDK.

**Comment by jchristn** [comment]
Thank you @sumitgoelpw !  Please let me know what we can do to make it even better for you.  Cheers sir.
