### ISSUE TITLE
method for get all events

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#2]
Currently, API only returns 100 results, and we have to use the offset to query again. It would be nice if a method is available to get all events. Something similar to https://github.com/sumitgoelpw/cloudgenix-api-client/blob/master/lib/utils.js#L17

**Comment by jchristn** [comment]
You got it @sumitgoelpw , I'll put it on the list!

**Comment by jchristn** [comment]
@sumitgoelpw I have an early version that I'd like to have you check out.  I'll commit the ```allevents``` branch for you to pull and paste a quick script here that you can use.  Please let me know if any issues.  Thanks!

**Comment by jchristn** [comment]
Here is the branch: https://github.com/CloudGenix/sdk-nodejs/tree/allevents

And the sample script I used for testing: https://github.com/CloudGenix/sdk-nodejs/blob/allevents/Misc/getAllEvents.js

On the implementation, there are a couple of things of which you may want to be aware:

- It uses promises with recursion internally
- It temporarily creates two variables off of global, one called _eventsQuery and another called _eventsResponse.  These are nullified after resolving the outer promise (made it easier than passing around a bunch of state during recursion)

Let me know if this works!

**Comment by StarryShark** [comment]
@jchristn Thank you for the quick response. I am going to test it now and will let you know in a bit.

**Comment by sumitgoelpw** [comment]
I am trying to test following query and there seem to some issue, but I don't yet what. I will provide more details soon.

```javascript
  {
    'query': {
      'site': [
        '14894519952040063',
        '15178596380300189',
        '15199292602710010'
      ],
      'type': ['alarm']
    },
    'view': {'summary': false}
  }
```

**Comment by StarryShark** [comment]
I am trying to test following query and there seem to some issue, but I don't know yet what. I will provide more details soon.

```javascript
  {
    'query': {
      'site': [ <active sites>],
      'type': ['alarm']
    },
    'view': {'summary': false}
  }
```

**Comment by StarryShark** [comment]
@jchristn I think your `JSON.parse()` change broke `getAllEvents()`. It's working fine until [Early version of getAllEvents](https://github.com/CloudGenix/sdk-nodejs/tree/7767025205be4acc5173250c6905472839c175ab). Please check.

**Comment by StarryShark** [comment]
According to the Events Query Format documentation, `query` is the only required field but,

*Not working*
```javascript
const events = await cgz.getAllEvents({'query': {}});
```

*Working*

```javascript
const events = await cgz.getAllEvents({
  'query': {},
  'severity': []
});
```

**Comment by jchristn** [comment]
Thanks Sumit, I think I know what happened.  Also I’ll update the docs.

Commit coming shortly.

**Comment by jchristn** [comment]
Hi Sumit, fixed here and tested: https://github.com/CloudGenix/sdk-nodejs/commit/6c9510e741761783c99c6d50a97946f1ad7a6f73

Updating the docs now.

**Comment by jchristn** [comment]
BTW npm updated to v1.1.1

**Comment by StarryShark** [comment]
Thank you @jchristn. I will test in the evening.
