### ISSUE TITLE
getSites return string instead of object

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#3]
I am using the following code, and it seems like getSites() is returning `string` instead of `object`. Is this expected behavior?

```javascript
const sites = await cgz.getSites();
console.log(typeof sites);
try {
  console.log(sites.items.length);
} catch (error) {
  console.log(error);
}
const jsonSites = JSON.parse(sites);
console.log(typeof jsonSites);
console.log(jsonSites.items.length);
```

**Comment by jchristn** [comment]
Ah, looks like I'm returning string on all of the APIs rather than doing a resolve(JSON.parse(data));.  I'll make this change and will include in the next commit/npm publish.  Will wait for your confirmation on the getAllEvents API first.  Thanks!

**Comment by jchristn** [comment]
This is resolved in the allevents branch: https://github.com/CloudGenix/sdk-nodejs/commit/978f162ac6987d867fe8a5d276c2b02bb8f08afb

I will commit to master and update npm once you confirm the getAllEvents API.

Thanks!

**Comment by StarryShark** [comment]
Thank you!
