### ISSUE TITLE
Feature request: getSites should have an option to return sites based on admin_status

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#4]
I think there are three admin statuses `active`, `disabled` and `monitor`. We should be able to get the sites by the admin status.

**Comment by jchristn** [comment]
Hi Sumit, I'm checking on whether or not the API itself supports this.

**Comment by jchristn** [comment]
Hi @sumitgoelpw I'm going to send you an email on this one and close the request.  Thanks, Joel
