### ISSUE TITLE
Update query_events version to 3.1

### ISSUE THREAD

**Issue by StarryShark** [CloudGenix/sdk-nodejs#5]
@jchristn, I was talking to @ebob9 today and came to know version 3.1 is available now with the acknowledgment feature. Please help to update the version.

**Comment by jchristn** [comment]
Hi @sumitgoelpw - just added branch ```events31``` (see https://github.com/CloudGenix/sdk-nodejs/tree/events31) and added ```Misc/acknowledgeEvent.js``` to test the API.  Please let me know if this helps (see https://github.com/CloudGenix/sdk-nodejs/blob/events31/Misc/acknowledgeEvent.js) - thanks, Joel

**Comment by StarryShark** [comment]
@jchristn thank you for working on it. My use case is to get the events that have not been acknowledged but the ability to acknowledge the event is helpful too. When do you plan to make a production release?

**Comment by jchristn** [comment]
@sumitgoelpw yes - you'll be able to add ```include_acknowledged: false``` in the query to retrieve events that are not yet acknowledged.  I'll get this packaged up today and submitted to npm.

**Comment by jchristn** [comment]
Hi jchristn!

A new version of the package cloudgenix (1.1.3) was published at 2018-05-01T16:19:59.128Z from
12.196.121.11. The shasum of this package was 729c87186e7327eee30cf9ddabba700ee0490cae.

If you have questions or security concerns, you can reply to this message or
email support@npmjs.com.

npm loves you.
